"""
Audit Deliverable Formatter for C-Suite.

Formats agent responses into a branded Growth Strategy Audit deliverable.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Any


@dataclass
class AuditSection:
    """A section of the audit deliverable."""

    title: str
    source_agent: str
    content: str


@dataclass
class AuditMetrics:
    """Metrics for the audit execution."""

    total_cost: float
    query_count: int
    execution_time_minutes: float
    cost_by_agent: dict[str, float]


class AuditFormatter:
    """Formats audit outputs into a branded deliverable."""

    def __init__(
        self,
        company_description: str,
        revenue: str | None = None,
        employees: int | None = None,
        industry: str | None = None,
    ):
        """
        Initialize the formatter.

        Args:
            company_description: Description of the company being audited
            revenue: Optional annual revenue (e.g., "$12M")
            employees: Optional employee count
            industry: Optional industry vertical
        """
        self.company_description = company_description
        self.revenue = revenue
        self.employees = employees
        self.industry = industry
        self.sections: list[AuditSection] = []
        self.synthesis: str = ""
        self.metrics: AuditMetrics | None = None

    def add_section(self, title: str, source_agent: str, content: str) -> None:
        """Add a section to the audit."""
        self.sections.append(AuditSection(title=title, source_agent=source_agent, content=content))

    def set_synthesis(self, synthesis: str) -> None:
        """Set the synthesis content."""
        self.synthesis = synthesis

    def set_metrics(self, metrics: AuditMetrics) -> None:
        """Set the audit metrics."""
        self.metrics = metrics

    def format_markdown(self) -> str:
        """Format the audit as a markdown document."""
        timestamp = datetime.now().strftime("%B %d, %Y")

        # Build company profile section
        profile_lines = [f"**Description:** {self.company_description}"]
        if self.revenue:
            profile_lines.append(f"**Annual Revenue:** {self.revenue}")
        if self.employees:
            profile_lines.append(f"**Employees:** {self.employees}")
        if self.industry:
            profile_lines.append(f"**Industry:** {self.industry}")

        company_profile = "\n".join(profile_lines)

        # Build sections content
        sections_md = ""
        for section in self.sections:
            sections_md += f"""
---

## {section.title}

*Analysis by {section.source_agent}*

{section.content}
"""

        # Build metrics section
        metrics_md = ""
        if self.metrics:
            cost_breakdown = ""
            if self.metrics.cost_by_agent:
                cost_breakdown = "\n".join(
                    f"  - {agent}: ${cost:.4f}"
                    for agent, cost in sorted(
                        self.metrics.cost_by_agent.items(), key=lambda x: -x[1]
                    )
                )

            metrics_md = f"""
---

## Audit Metrics

| Metric | Value |
|--------|-------|
| Total API Cost | ${self.metrics.total_cost:.2f} |
| Queries Executed | {self.metrics.query_count} |
| Execution Time | {self.metrics.execution_time_minutes:.1f} minutes |

### Cost by Agent
{cost_breakdown}
"""

        # Assemble the full document
        # Truncate long descriptions for header
        desc_preview = self.company_description[:50]
        desc_suffix = "..." if len(self.company_description) > 50 else ""

        return f"""# Growth Strategy Audit

**Prepared for:** {desc_preview}{desc_suffix}
**Date:** {timestamp}
**Prepared by:** Cardinal Element C-Suite AI Advisory Team

---

## Company Profile

{company_profile}

{sections_md}

---

## Strategic Synthesis

*Integrated analysis across all perspectives*

{self.synthesis}

{metrics_md}

---

*This audit was generated by Cardinal Element's C-Suite AI advisory platform.
For questions or follow-up analysis, contact your Cardinal Element advisor.*
"""

    def format_console_summary(self) -> dict[str, Any]:
        """Format a summary suitable for console display."""
        return {
            "company": self.company_description[:50],
            "sections": len(self.sections),
            "has_synthesis": bool(self.synthesis),
            "metrics": {
                "cost": f"${self.metrics.total_cost:.2f}" if self.metrics else "N/A",
                "queries": self.metrics.query_count if self.metrics else 0,
                "time": f"{self.metrics.execution_time_minutes:.1f} min"
                if self.metrics
                else "N/A",
            },
        }
